name: Codex Agent

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  workflow_call:
    inputs:
      timeout_minutes:
        description: 'Timeout in minutes for the workflow'
        type: number
        default: 10
      max_retries:
        description: 'Maximum number of retries for verification'
        type: number
        default: 5
      retry_wait_base:
        description: 'Base wait time in seconds for exponential backoff'
        type: number
        default: 2

jobs:
  codex:
    if: |
      github.event_name == 'workflow_call' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@codex')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@codex')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@codex')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@codex') || contains(github.event.issue.title, '@codex')))
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes || 10 }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ env.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "codex-bot@openai.com"
          git config --global user.name "Codex Bot"

      - name: Get conversation context
        id: context
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          # Use same context gathering script from Claude workflow
          script: |
            // [Same script as Claude workflow lines 50-199]

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Codex Agent
        run: |
          # Install dependencies if needed
          npm install openai

          # Create and run Codex wrapper script
          node scripts/ai/codex-agent.js \
            --context "${{ steps.context.outputs.conversation_context }}" \
            --request "${{ steps.context.outputs.current_request }}" \
            --repo "${{ github.repository }}" \
            --issue "${{ github.event.issue.number || github.event.pull_request.number }}"

      - name: Post response
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('codex-response.md', 'utf8');

            const issueNumber = context.issue.number || context.payload.pull_request?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: response
              });
            }