name: 'Mask Secrets'
description: 'Masks sensitive values in GitHub Actions logs to prevent credential exposure'
author: 'Security Team'

inputs:
  github_token:
    description: 'GitHub token to mask'
    required: false
    default: ''
  ai_api_key:
    description: 'AI API key to mask'
    required: false
    default: ''
  gh_pat:
    description: 'GitHub Personal Access Token to mask'
    required: false
    default: ''
  custom_secrets:
    description: 'Comma-separated list of additional secrets to mask'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Mask standard secrets
      shell: bash
      run: |
        # Security: Mask all provided secrets to prevent exposure in logs
        # OWASP: A09:2021 - Security Logging and Monitoring Failures

        echo "::group::Initializing secret masking..."

        # Mask GitHub token if provided
        if [[ -n "${{ inputs.github_token }}" ]]; then
          echo "::add-mask::${{ inputs.github_token }}"
          echo "✓ GitHub token masked"
        fi

        # Mask AI API key if provided
        if [[ -n "${{ inputs.ai_api_key }}" ]]; then
          echo "::add-mask::${{ inputs.ai_api_key }}"
          echo "✓ AI API key masked"
        fi

        # Mask GitHub PAT if provided
        if [[ -n "${{ inputs.gh_pat }}" ]]; then
          echo "::add-mask::${{ inputs.gh_pat }}"
          echo "✓ GitHub PAT masked"
        fi

        # Mask custom secrets if provided
        if [[ -n "${{ inputs.custom_secrets }}" ]]; then
          IFS=',' read -ra SECRETS <<< "${{ inputs.custom_secrets }}"
          for secret in "${SECRETS[@]}"; do
            if [[ -n "${secret}" ]]; then
              echo "::add-mask::${secret}"
              echo "✓ Custom secret masked"
            fi
          done
        fi

        echo "::endgroup::"
        echo "✅ Secret masking initialized successfully"

    - name: Set security flags
      shell: bash
      run: |
        # Set environment variables to enhance security
        echo "::group::Setting security flags..."

        # Disable command echoing to prevent accidental secret exposure
        set +x

        # Set secure environment variables
        echo "ACTIONS_STEP_DEBUG=false" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_DEBUG=false" >> $GITHUB_ENV

        echo "✅ Security flags configured"
        echo "::endgroup::"