name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'lib/**'
      - '*.js'
      - '*.ts'
      - '*.py'
      - '*.go'
      - '*.java'
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number

# Minimal permissions - security best practice
permissions:
  contents: read
  pull-requests: write
  issues: read

env:
  # AI Configuration
  AI_MODEL: gpt-4
  AI_PROVIDER: openai
  AI_TEMPERATURE: 0.3
  AI_MAX_TOKENS: 2000
  AI_FOCUS_AREAS: security,performance,best-practices,code-quality

  # Review Configuration
  MIN_SCORE_FOR_APPROVAL: 85
  SKIP_DRAFT_PRS: true
  MAX_FILES_FOR_REVIEW: 20
  MAX_DIFF_SIZE_KB: 500

  # Performance Configuration
  SPARSE_CHECKOUT: true
  ENABLE_CACHING: true

jobs:
  ai-review:
    name: AI Code Review
    runs-on: [self-hosted, linux, ai-agent]
    timeout-minutes: 15

    # Skip draft PRs if configured
    if: |
      (env.SKIP_DRAFT_PRS != 'true' || !github.event.pull_request.draft) &&
      github.event.action != 'submitted'

    steps:
      - name: Setup AI Agent Environment
        uses: ./.github/actions/setup-ai-agent
        with:
          sparse-checkout: ${{ env.SPARSE_CHECKOUT }}
          checkout-paths: |
            .github/
            src/
            lib/
            package.json
            requirements.txt
            go.mod
            pom.xml
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Check PR Size
        id: pr-size
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          # Get PR file count and changes
          CHANGED_FILES=$(gh pr view "$PR_NUMBER" --json changedFiles --jq '.changedFiles')
          ADDITIONS=$(gh pr view "$PR_NUMBER" --json additions --jq '.additions')
          DELETIONS=$(gh pr view "$PR_NUMBER" --json deletions --jq '.deletions')

          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "additions=$ADDITIONS" >> $GITHUB_OUTPUT
          echo "deletions=$DELETIONS" >> $GITHUB_OUTPUT

          # Check if PR is too large
          if [ "$CHANGED_FILES" -gt "$MAX_FILES_FOR_REVIEW" ]; then
            echo "pr_too_large=true" >> $GITHUB_OUTPUT
            echo "⚠️ PR has $CHANGED_FILES files (max: $MAX_FILES_FOR_REVIEW)"
          else
            echo "pr_too_large=false" >> $GITHUB_OUTPUT
            echo "✅ PR size acceptable: $CHANGED_FILES files"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Size Warning
        if: steps.pr-size.outputs.pr_too_large == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          gh pr comment "$PR_NUMBER" --body "## ⚠️ PR Too Large for AI Review

          This PR changes **${{ steps.pr-size.outputs.changed_files }}** files, which exceeds the maximum of **$MAX_FILES_FOR_REVIEW** files for automated AI review.

          **Recommendation**: Consider breaking this PR into smaller, more focused changes for better review quality.

          **Manual review required.**"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check GitHub API Rate Limit
        if: steps.pr-size.outputs.pr_too_large != 'true'
        id: rate-limit
        run: |
          REMAINING=$(gh api rate_limit --jq '.rate.remaining')
          LIMIT=$(gh api rate_limit --jq '.rate.limit')
          RESET=$(gh api rate_limit --jq '.rate.reset')

          echo "remaining=$REMAINING" >> $GITHUB_OUTPUT
          echo "limit=$LIMIT" >> $GITHUB_OUTPUT

          echo "📊 GitHub API Rate Limit: $REMAINING/$LIMIT remaining"

          if [ "$REMAINING" -lt 100 ]; then
            echo "⚠️ Low rate limit: $REMAINING requests remaining"
            CURRENT_TIME=$(date +%s)
            WAIT_TIME=$((RESET - CURRENT_TIME))
            echo "wait_seconds=$WAIT_TIME" >> $GITHUB_OUTPUT

            if [ "$WAIT_TIME" -gt 900 ]; then
              echo "❌ Wait time too long: $((WAIT_TIME / 60)) minutes"
              exit 1
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Wait for Rate Limit Reset
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          steps.rate-limit.outputs.wait_seconds != '' &&
          steps.rate-limit.outputs.wait_seconds != '0'
        run: |
          WAIT_TIME=${{ steps.rate-limit.outputs.wait_seconds }}
          echo "⏳ Waiting $WAIT_TIME seconds for rate limit reset..."
          sleep "$WAIT_TIME"

      - name: Extract PR Context
        if: steps.pr-size.outputs.pr_too_large != 'true'
        id: pr-context
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          echo "📥 Extracting PR context for #$PR_NUMBER..."

          # Run context extraction script
          bash .github/scripts/extract-pr-context.sh "$PR_NUMBER" pr-context.json

          # Check context file size
          CONTEXT_SIZE=$(wc -c < pr-context.json)
          echo "context_size=$CONTEXT_SIZE" >> $GITHUB_OUTPUT
          echo "📦 Context size: $((CONTEXT_SIZE / 1024)) KB"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_MODEL: ${{ env.AI_MODEL }}

      - name: Check if Already Reviewed
        if: steps.pr-size.outputs.pr_too_large != 'true'
        id: check-reviewed
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          # Check for existing AI review comment
          EXISTING_REVIEW=$(gh pr view "$PR_NUMBER" --json comments \
            --jq '[.comments[] | select(.author.login == "github-actions[bot]" and (.body | contains("AI Code Review")))] | length')

          if [ "$EXISTING_REVIEW" -gt 0 ]; then
            echo "already_reviewed=true" >> $GITHUB_OUTPUT
            echo "ℹ️ PR already has AI review comment"
          else
            echo "already_reviewed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call AI for Review
        if: steps.pr-size.outputs.pr_too_large != 'true'
        id: ai-review
        run: |
          echo "🤖 Requesting AI code review..."

          # Run AI review script with retry logic
          bash .github/scripts/ai-pr-review.sh \
            --context-file pr-context.json \
            --output-file ai-response.json \
            --model "$AI_MODEL" \
            --provider "$AI_PROVIDER" \
            --temperature "$AI_TEMPERATURE" \
            --max-tokens "$AI_MAX_TOKENS" \
            --focus-areas "$AI_FOCUS_AREAS"

          # Extract review metadata
          STATUS=$(jq -r '.status' ai-response.json)
          SCORE=$(jq -r '.result.score // 0' ai-response.json)
          COMMENT_COUNT=$(jq -r '.result.comments | length' ai-response.json)

          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "score=$SCORE" >> $GITHUB_OUTPUT
          echo "comment_count=$COMMENT_COUNT" >> $GITHUB_OUTPUT

          echo "✅ AI Review completed: Score $SCORE/100, $COMMENT_COUNT issues found"
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Validate AI Response
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          steps.ai-review.outcome == 'success'
        id: validate
        run: |
          echo "✔️ Validating AI response schema..."

          if bash .github/scripts/validate-schema.sh \
               --schema .github/schemas/ai-response-schema.json \
               --data ai-response.json; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "✅ Response schema valid"
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "❌ Invalid response schema"
          fi
        continue-on-error: true

      - name: Post Review Comment
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          steps.ai-review.outcome == 'success' &&
          steps.validate.outputs.valid == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          echo "💬 Posting review comment on PR #$PR_NUMBER..."

          # Process AI response and generate markdown
          bash .github/scripts/process-ai-response.sh ai-response.json "$PR_NUMBER"

          # Post main review comment
          if [ -f review-comment.md ]; then
            if [ "${{ steps.check-reviewed.outputs.already_reviewed }}" == "true" ]; then
              # Update existing review
              echo "🔄 Updating existing review comment..."
              gh pr comment "$PR_NUMBER" --body "$(cat review-comment.md)

              ---
              *🔄 Updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')*"
            else
              # Post new review
              gh pr comment "$PR_NUMBER" --body "$(cat review-comment.md)"
            fi
          fi

          echo "✅ Review comment posted"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Review Label
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          steps.ai-review.outcome == 'success'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"
          SCORE="${{ steps.ai-review.outputs.score }}"

          # Add appropriate label based on score
          if [ "$SCORE" -ge 90 ]; then
            LABEL="ai-approved"
          elif [ "$SCORE" -ge 70 ]; then
            LABEL="ai-reviewed"
          else
            LABEL="ai-needs-work"
          fi

          gh pr edit "$PR_NUMBER" --add-label "$LABEL"
          echo "🏷️ Added label: $LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Auto-Approve High Quality PRs
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          steps.ai-review.outputs.score >= env.MIN_SCORE_FOR_APPROVAL &&
          steps.ai-review.outputs.comment_count == '0'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          echo "✅ PR score (${{ steps.ai-review.outputs.score }}) meets approval threshold ($MIN_SCORE_FOR_APPROVAL)"
          echo "👍 Auto-approving PR..."

          gh pr review "$PR_NUMBER" \
            --approve \
            --body "**🤖 Automated Approval**

          This PR has been automatically approved by the AI reviewer based on:
          - Quality score: **${{ steps.ai-review.outputs.score }}/100**
          - No issues found
          - All checks passed

          *A human review is still recommended before merging.*"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Handle AI Failure
        if: |
          steps.pr-size.outputs.pr_too_large != 'true' &&
          (steps.ai-review.outcome == 'failure' || steps.validate.outputs.valid == 'false')
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || inputs.pr_number }}"

          echo "❌ AI review failed, posting error comment..."

          gh pr comment "$PR_NUMBER" --body "## ❌ AI Review Failed

          The automated AI review encountered an error and could not complete.

          **Possible causes:**
          - AI API rate limit exceeded
          - AI service temporarily unavailable
          - Response validation failed

          **Next steps:**
          - Manual review is required
          - You can retry the workflow manually
          - Check workflow logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          *This PR will require human review.*"

          # Send error notification
          bash .github/scripts/notify-error.sh \
            --workflow "${{ github.workflow }}" \
            --error "AI review failed for PR #$PR_NUMBER" \
            --run-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Review Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ai-review-artifacts-pr-${{ github.event.pull_request.number || inputs.pr_number }}
          path: |
            pr-context.json
            ai-response.json
            review-comment.md
          retention-days: 30
        continue-on-error: true

      - name: Record Metrics
        if: always()
        run: |
          echo "📊 Recording workflow metrics..."

          cat > metrics.json <<EOF
          {
            "workflow": "${{ github.workflow }}",
            "pr_number": ${{ github.event.pull_request.number || inputs.pr_number }},
            "outcome": "${{ job.status }}",
            "score": ${{ steps.ai-review.outputs.score || 0 }},
            "issues_found": ${{ steps.ai-review.outputs.comment_count || 0 }},
            "files_changed": ${{ steps.pr-size.outputs.changed_files || 0 }},
            "additions": ${{ steps.pr-size.outputs.additions || 0 }},
            "deletions": ${{ steps.pr-size.outputs.deletions || 0 }},
            "runtime_seconds": ${{ github.job.duration || 0 }},
            "timestamp": "$(date -Iseconds)"
          }
          EOF

          echo "✅ Metrics recorded"
        continue-on-error: true
