#!/usr/bin/env bash
# Integration Test: AI Issue Comment Workflow
# Tests AI agent responses to issue comments

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/test-helpers.sh
source "${SCRIPT_DIR}/../lib/test-helpers.sh"

# Test configuration
readonly TEST_WORKFLOW="ai-issue-comment.yml"
readonly TEST_SCRIPT="${SCRIPT_DIR}/../../../scripts/ai-agent.sh"
readonly TEST_OUTPUT_DIR="/tmp/test-ai-issue-comment"

# Setup test environment
setup() {
    log_info "Setting up AI Issue Comment tests..."

    mkdir -p "$TEST_OUTPUT_DIR"

    setup_mock_github_api "$TEST_OUTPUT_DIR/mock-github"
    setup_mock_ai_api "$TEST_OUTPUT_DIR/mock-ai"

    export GITHUB_TOKEN="test-token-123"
    export AI_API_KEY="test-ai-key-456"
    export GITHUB_REPOSITORY="test-org/test-repo"
}

teardown() {
    log_info "Tearing down AI Issue Comment tests..."

    teardown_mock_github_api "$TEST_OUTPUT_DIR/mock-github"
    teardown_mock_ai_api "$TEST_OUTPUT_DIR/mock-ai"

    if [[ "$CLEANUP_ON_SUCCESS" == "true" ]]; then
        rm -rf "$TEST_OUTPUT_DIR"
    fi
}

# Test 1: Workflow triggers on /agent comment
test_workflow_trigger_on_agent_command() {
    log_test "Test: Workflow triggers on /agent comment"

    local comment_body="/agent please analyze this issue"

    if echo "$comment_body" | grep -q "/agent"; then
        log_info "Trigger detected in comment"
        return 0
    else
        log_fail "Trigger not detected"
        return 1
    fi
}

# Test 2: Workflow validates issue number
test_workflow_validates_issue_number() {
    log_test "Test: Workflow validates issue number"

    local issue_num="456"

    if [[ "$issue_num" =~ ^[0-9]+$ ]]; then
        return 0
    else
        log_fail "Invalid issue number: $issue_num"
        return 1
    fi
}

# Test 3: Workflow detects bot loops
test_workflow_detects_bot_loop() {
    log_test "Test: Workflow detects bot loops"

    # Simulate recent bot comments
    local recent_bot_comments=4
    local threshold=3

    if [[ $recent_bot_comments -ge $threshold ]]; then
        log_info "Bot loop detected: $recent_bot_comments >= $threshold"
        return 0
    else
        log_fail "Bot loop not detected"
        return 1
    fi
}

# Test 4: Workflow extracts issue context
test_workflow_extracts_issue_context() {
    log_test "Test: Workflow extracts issue context"

    local issue_data
    issue_data=$(create_test_issue_data 456 "$TEST_OUTPUT_DIR/issue-456.json")

    assert_file_exists "$issue_data"
    assert_json_valid "$(cat "$issue_data")"

    local title
    title=$(jq -r '.title' "$issue_data")
    assert_contains "$title" "Test Issue"

    local labels
    labels=$(jq -r '.labels[].name' "$issue_data" | paste -sd "," -)
    assert_contains "$labels" "bug"
}

# Test 5: Workflow extracts user query from comment
test_workflow_extracts_user_query() {
    log_test "Test: Workflow extracts user query"

    local comment_body="/agent What is the root cause of this issue?"
    local trigger_prefix="/agent"

    local query
    query=$(echo "$comment_body" | sed "s|$trigger_prefix||g" | sed 's/^[[:space:]]*//g')

    assert_contains "$query" "What is the root cause"
    assert_not_contains "$query" "/agent"
}

# Test 6: Workflow handles empty query
test_workflow_handles_empty_query() {
    log_test "Test: Workflow handles empty query"

    local comment_body="/agent"
    local trigger_prefix="/agent"

    local query
    query=$(echo "$comment_body" | sed "s|$trigger_prefix||g" | sed 's/^[[:space:]]*//g')

    if [[ -z "$query" ]]; then
        query="Please provide assistance with this issue."
        log_info "Default query set: $query"
    fi

    assert_contains "$query" "assistance"
}

# Test 7: Script generates valid AI response
test_script_generates_valid_response() {
    log_test "Test: Script generates valid AI response"

    cat > "$TEST_OUTPUT_DIR/response.json" << 'EOF'
{
  "response": {
    "body": "Based on the issue description, here is my analysis...",
    "type": "comment",
    "suggested_labels": ["needs-investigation", "priority-high"]
  },
  "metadata": {
    "model": "claude-3-opus",
    "timestamp": "2024-01-01T00:00:00Z",
    "issue_number": 456
  }
}
EOF

    local response_json
    response_json=$(cat "$TEST_OUTPUT_DIR/response.json")

    assert_json_valid "$response_json"
    assert_json_has_key "$response_json" "response"
    assert_json_has_key "$response_json" "metadata"

    local response_body
    response_body=$(echo "$response_json" | jq -r '.response.body')
    assert_contains "$response_body" "analysis"
}

# Test 8: Workflow posts AI response to issue
test_workflow_posts_response() {
    log_test "Test: Workflow posts AI response"

    local issue_number=456
    local response_body="This is an AI-generated response."

    # Create response file
    cat > "$TEST_OUTPUT_DIR/post-response.md" << EOF
$response_body

---
*This response was generated by an AI agent. If you need further assistance, mention \`/agent\` in a comment.*
EOF

    assert_file_exists "$TEST_OUTPUT_DIR/post-response.md"

    local content
    content=$(cat "$TEST_OUTPUT_DIR/post-response.md")
    assert_contains "$content" "AI agent"
}

# Test 9: Workflow applies suggested labels
test_workflow_applies_suggested_labels() {
    log_test "Test: Workflow applies suggested labels"

    local response_json='{"response": {"suggested_labels": ["bug", "needs-triage"]}}'

    local suggested_labels
    suggested_labels=$(echo "$response_json" | jq -r '.response.suggested_labels | join(",")')

    assert_contains "$suggested_labels" "bug"
    assert_contains "$suggested_labels" "needs-triage"
}

# Test 10: Workflow handles bot loop mitigation
test_workflow_handles_bot_loop_mitigation() {
    log_test "Test: Workflow handles bot loop mitigation"

    local loop_detected=true
    local mitigation_posted=false

    if [[ "$loop_detected" == "true" ]]; then
        # Post mitigation message
        mitigation_posted=true
        log_info "Bot loop mitigation posted"
    fi

    if [[ "$mitigation_posted" == "true" ]]; then
        return 0
    else
        log_fail "Mitigation not posted"
        return 1
    fi
}

# Test 11: Workflow handles agent failure
test_workflow_handles_agent_failure() {
    log_test "Test: Workflow handles agent failure"

    local error_occurred=true
    local error_notification="AI Agent Error"

    if [[ "$error_occurred" == "true" ]]; then
        log_info "Error notification: $error_notification"
        return 0
    else
        log_fail "Error not handled"
        return 1
    fi
}

# Test 12: End-to-end issue comment flow
test_issue_comment_full_flow() {
    log_test "Test: Complete issue comment flow"

    local issue_number=456

    # Step 1: Create test issue
    local issue_data
    issue_data=$(create_test_issue_data "$issue_number" "$TEST_OUTPUT_DIR/e2e-issue.json")
    assert_file_exists "$issue_data"

    # Step 2: Extract user query
    local comment_body="/agent What should we do about this?"
    local query
    query=$(echo "$comment_body" | sed 's|/agent||g' | sed 's/^[[:space:]]*//g')
    assert_contains "$query" "What should we do"

    # Step 3: Generate AI response
    cat > "$TEST_OUTPUT_DIR/e2e-response.json" << 'EOF'
{
  "response": {
    "body": "Here is my recommendation based on the issue context...",
    "type": "comment",
    "suggested_labels": []
  }
}
EOF

    assert_file_exists "$TEST_OUTPUT_DIR/e2e-response.json"

    # Step 4: Parse response
    local response
    response=$(jq -r '.response.body' "$TEST_OUTPUT_DIR/e2e-response.json")
    assert_contains "$response" "recommendation"

    # Step 5: Post response (mocked)
    log_info "Response would be posted to issue #$issue_number"
}

# Test 13: Workflow skips non-trigger comments
test_workflow_skips_non_trigger_comments() {
    log_test "Test: Workflow skips non-trigger comments"

    local comment_body="This is a regular comment without trigger"

    if echo "$comment_body" | grep -q "/agent"; then
        log_fail "Should not trigger on regular comment"
        return 1
    else
        log_info "Correctly skipped non-trigger comment"
        return 0
    fi
}

# Test 14: Workflow extracts context with max comments limit
test_workflow_max_context_comments() {
    log_test "Test: Workflow respects max context comments"

    local max_context=10
    local total_comments=15

    local comments_to_fetch=$((total_comments < max_context ? total_comments : max_context))

    assert_equals "$max_context" "$comments_to_fetch"
}

# Test 15: Workflow performs cleanup
test_workflow_cleanup() {
    log_test "Test: Workflow performs cleanup"

    local temp_dir="$TEST_OUTPUT_DIR/agent-cleanup-test"
    mkdir -p "$temp_dir"

    # Simulate cleanup
    rm -rf "$temp_dir"

    assert_file_not_exists "$temp_dir/should-be-deleted"
}

# Main test execution
main() {
    log_info "Starting AI Issue Comment Workflow Integration Tests"
    log_info "===================================================="

    setup

    run_test "Workflow triggers on /agent command" "test_workflow_trigger_on_agent_command" || true
    run_test "Workflow validates issue number" "test_workflow_validates_issue_number" || true
    run_test "Workflow detects bot loops" "test_workflow_detects_bot_loop" || true
    run_test "Workflow extracts issue context" "test_workflow_extracts_issue_context" || true
    run_test "Workflow extracts user query" "test_workflow_extracts_user_query" || true
    run_test "Workflow handles empty query" "test_workflow_handles_empty_query" || true
    run_test "Script generates valid response" "test_script_generates_valid_response" || true
    run_test "Workflow posts response" "test_workflow_posts_response" || true
    run_test "Workflow applies suggested labels" "test_workflow_applies_suggested_labels" || true
    run_test "Workflow handles bot loop mitigation" "test_workflow_handles_bot_loop_mitigation" || true
    run_test "Workflow handles agent failure" "test_workflow_handles_agent_failure" || true
    run_test "Complete issue comment flow" "test_issue_comment_full_flow" || true
    run_test "Workflow skips non-trigger comments" "test_workflow_skips_non_trigger_comments" || true
    run_test "Workflow max context comments" "test_workflow_max_context_comments" || true
    run_test "Workflow performs cleanup" "test_workflow_cleanup" || true

    teardown

    print_test_summary
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
